# Generated by Django 4.2.2 on 2023-09-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0008_delete_producttransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),

    ]
