# Generated by Django 4.2.2 on 2023-09-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0009_alter_selectedproduct_quantity_and_more'),
    ]


