# Generated by Django 4.2.2 on 2023-09-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0010_delete_producttransfer'),
    ]


